DROP TABLE IF EXISTS Commentaire;
DROP TABLE IF EXISTS Vehicule;
DROP TABLE IF EXISTS Sortie;
DROP TABLE IF EXISTS Lieu;
DROP TABLE IF EXISTS Message;
DROP TABLE IF EXISTS CompteRendu;
DROP TABLE IF EXISTS Adherent;
