CREATE TABLE Contact(
  ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Nom VARCHAR(40),
  Prenom VARCHAR(30),
  Adresse VARCHAR(100),
  NumTel VARCHAR(10),
  Mail VARCHAR(30)
) ENGINE = InnoDB;
