BEGIN;

DROP TABLE IF EXISTS InscriptionEnAttente;
DROP TABLE IF EXISTS PratiqueEvent;
DROP TABLE IF EXISTS Commentaire;
DROP TABLE IF EXISTS Cours;
DROP TABLE IF EXISTS Pratique;
DROP TABLE IF EXISTS Certificat;
DROP TABLE IF EXISTS AssuranceAdh;
DROP TABLE IF EXISTS Sujet;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS Lieu;
DROP TABLE IF EXISTS Message;
DROP TABLE IF EXISTS CompteRendu;
DROP TABLE IF EXISTS Utilisateur;
DROP TABLE IF EXISTS Contact;

COMMIT;
